<?php
$pt_templets_sortnav['1']['name']='奇幻·玄幻';
$pt_templets_sortnav['1']['id']='1';
$pt_templets_sortnav['2']['name']='武侠·仙侠';
$pt_templets_sortnav['2']['id']='2';
$pt_templets_sortnav['3']['name']='历史·军事';
$pt_templets_sortnav['3']['id']='3';
$pt_templets_sortnav['4']['name']='都市·言情';
$pt_templets_sortnav['4']['id']='4';
$pt_templets_sortnav['5']['name']='竞技·游戏';
$pt_templets_sortnav['5']['id']='5';
$pt_templets_sortnav['6']['name']='科幻·灵异';
$pt_templets_sortnav['6']['id']='6';
$pt_templets_sortnav['7']['name']='美文·同人';
$pt_templets_sortnav['7']['id']='7';
$pt_templets_sortnav['8']['name']='动画·漫画';
$pt_templets_sortnav['8']['id']='8';
?>