<?php
$pt_templets_name='纵横中文网模板';
$pt_templets_author='杰少Pakey';
$pt_templets_copyurl='http://www.zongheng.com';
$pt_templets_demourl='http://www.kashu.in';
$pt_templets_nav['1']['name']='网站首页';
$pt_templets_nav['1']['url']='index.php';
$pt_templets_nav['2']['name']='分类列表';
$pt_templets_nav['2']['url']='sort.php';
$pt_templets_nav['3']['name']='全本小说';
$pt_templets_nav['3']['url']='over.php';
$pt_templets_nav['4']['name']='小说排行';
$pt_templets_nav['4']['url']='top.php';
$pt_templets_nav['5']['name']='全本排行';
$pt_templets_nav['5']['url']='topover.php';
$pt_templets_nav['6']['name']='在线阅读';
$pt_templets_nav['6']['url']='#';
$pt_templets_nav['7']['name']='控制面板';
$pt_templets_nav['7']['url']='user/';
$pt_templets_nav['8']['name']='我的书架';
$pt_templets_nav['8']['url']='user/usermark.php';
$pt_templets_nav['9']['name']='站长博客';
$pt_templets_nav['9']['url']='http://www.pakey.net';
?>